services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@db:3306/Facturation
    ports:
      - "9000:9000" # Port PHP-FPM
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Facturation
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
